# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder ".", "/home/vagrant/project"

  config.vm.provision "shell", inline: <<-SHELL
    add-apt-repository ppa:keithw/mahimahi
    apt-get update
    apt-get install -y build-essential git debhelper autotools-dev \
      dh-autoreconf iptables protobuf-compiler libprotobuf-dev pkg-config \
      libssl-dev dnsmasq-base ssl-cert libxcb-present-dev libcairo2-dev \
      libpango1.0-dev iproute2 apache2-dev apache2-bin iptables dnsmasq-base \
      gnuplot iproute2 apache2-api-20120211 libwww-perl mahimahi

    sysctl -w net.ipv4.ip_forward=1

    (cd /home/vagrant/project/sourdough && ./autogen.sh && ./configure && make)
  SHELL
end
